# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeezerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods
  
  pod 'Swinject'

  # Pods for DeezerDemo

  target 'DeezerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeezerDemoUITests' do
    # Pods for testing
  end

end
